name: Output Issue Details

on:
  issues:
    types: [opened]  # Trigger the workflow when a new issue is opened

jobs:
  display-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Issue Title
        run: echo "Issue Title: ${{ github.event.issue.title }}"

      - name: Display Issue Body
        run: echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Display Full GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"